# Generated by Django 3.0.6 on 2020-06-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('mail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('key_words', models.CharField(blank=True, max_length=300)),
                ('info_about', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_editado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60, unique=True)),
                ('area', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_asignacion_trabajador', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='hidden', max_length=10)),
                ('descripcion', models.TextField()),
                ('archivos', models.FileField(blank=True, null=True, upload_to='')),
                ('archivo_trabajador', models.FileField(blank=True, null=True, upload_to='')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fecha_editado', models.DateTimeField(auto_now=True)),
                ('publicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicador', to='MyGrades_App.Usuario')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador', to='MyGrades_App.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta_Bancaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=70)),
                ('numero_cedula', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_banco', models.CharField(max_length=40)),
                ('tipo_cuenta', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='MyGrades_App.Usuario')),
            ],
        ),
    ]
