# Generated by Django 3.0.6 on 2020-05-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=15)),
                ('dato', models.FileField(upload_to='')),
                ('tamaño', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=15)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('fecha_asignacion_trabajador', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('archivos', models.ManyToManyField(to='MyGrades_App.Archivo')),
                ('publicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicador', to='MyGrades_App.Usuario')),
                ('trabajador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador', to='MyGrades_App.Usuario')),
            ],
        ),
    ]
