# Generated by Django 3.0.6 on 2020-06-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='archivos',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='archivos',
            field=models.ManyToManyField(to='MyGrades_App.Archivo'),
        ),
    ]
