# Generated by Django 3.0.6 on 2020-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='archivos',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='archivos',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(default='publicado', max_length=10),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_asignacion_trabajador',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
