# Generated by Django 3.0.6 on 2020-05-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0002_auto_20200523_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_asignacion_trabajador',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_entrega',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_expiracion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
