# Generated by Django 3.0.7 on 2020-06-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0003_auto_20200626_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
    ]
