# Generated by Django 3.0.6 on 2020-05-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0003_auto_20200523_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
