# Generated by Django 3.0.6 on 2020-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0004_auto_20200524_0352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
