# Generated by Django 3.0.6 on 2020-07-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0005_auto_20200705_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='archivos',
            field=models.ManyToManyField(null=True, related_name='archivos', to='MyGrades_App.Archivo'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='archivos_trabajador',
            field=models.ManyToManyField(null=True, related_name='archivos_trabajador', to='MyGrades_App.Archivo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='info_about',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='key_words',
            field=models.CharField(blank=True, default=',,', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mail',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
