# Generated by Django 3.0.6 on 2020-06-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0006_auto_20200531_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_asignacion_trabajador',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador', to='MyGrades_App.Usuario'),
        ),
        migrations.CreateModel(
            name='Cuenta_Bancaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=70)),
                ('numero_cedula', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_banco', models.CharField(max_length=40)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='MyGrades_App.Usuario')),
            ],
        ),
    ]
