# Generated by Django 3.0.6 on 2020-06-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0007_auto_20200603_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta_Bancaria',
        ),
    ]
