# Generated by Django 3.0.6 on 2020-08-27 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0007_auto_20200827_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
