# Generated by Django 3.0.6 on 2020-08-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0008_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderID', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=150)),
                ('codigo_estado', models.CharField(max_length=150)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('fecha_editado', models.DateTimeField(auto_now=True)),
                ('trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyGrades_App.Trabajo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyGrades_App.Usuario')),
            ],
        ),
    ]
