# Generated by Django 3.0.6 on 2020-06-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0009_cuenta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='numero_cuenta',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='titulo',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
