# Generated by Django 3.0.6 on 2020-06-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0010_auto_20200605_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='archivo_trabajador',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
