# Generated by Django 3.1 on 2020-09-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0010_auto_20200904_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customersupport',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
