# Generated by Django 3.0.6 on 2020-06-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0011_trabajo_archivo_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='fecha_editado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='info_about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='key_words',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(default='hidden', max_length=10),
        ),
    ]
