# Generated by Django 3.1 on 2020-09-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0012_auto_20200906_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta_Bancaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(max_length=20)),
                ('nombre_apellido', models.CharField(max_length=70)),
                ('cedula_ruc', models.CharField(max_length=15)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='MyGrades_App.usuario')),
            ],
        ),
    ]
