# Generated by Django 3.1 on 2020-09-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0013_cuenta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupport',
            name='status',
            field=models.CharField(default='open', max_length=10),
        ),
        migrations.DeleteModel(
            name='Cuenta_Bancaria',
        ),
    ]
