# Generated by Django 3.1 on 2020-09-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0015_cuenta_bancaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta_bancaria',
            old_name='nombre_institucion',
            new_name='institucion',
        ),
    ]
