# Generated by Django 3.1 on 2020-09-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0016_auto_20200908_0253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
