# Generated by Django 3.1 on 2020-09-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0018_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
