# Generated by Django 3.1 on 2020-09-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGrades_App', '0020_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='cedula_ruc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='institucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='descripcion',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
